In [1]:
from StarV.util.load import load_sigmoidal_networks
from StarV.verifier.certifier import certifyRobustness
from tabulate import tabulate

In [2]:
data_type = 'mnist'
net_size = 'small'
func = 'tanh'

depth_reduction = 2
relaxation_factor = 0.0

epsilon = 0.02
verification_method = 'BFS'
reachability_method = 'approx'
lp_solver = 'gurobi'

parallel_processing = None
show = True

net, image, label = load_sigmoidal_networks(data_type=data_type, net_size=net_size, func=func)

if show:
    print('epsilon: {}'.format(epsilon))
    print('depth reduction: {}'.format(depth_reduction))
    print('relaxation_factor: {}'.format(relaxation_factor))
    print('verification_method: {}'.format(verification_method))
    print('reachability_method: {}'.format(reachability_method))
    print('lp_solver: {}\n'.format(lp_solver))
    net.info()

rb2, vt2 =certifyRobustness (
    net = net, 
    input = image, 
    epsilon = epsilon, 
    veriMethod = verification_method, 
    reachMethod = reachability_method, 
    lp_solver = lp_solver, 
    pool = parallel_processing, 
    RF = relaxation_factor, 
    DR = depth_reduction, 
    show=show
)

epsilon: 0.02
depth reduction: 2
relaxation_factor: 0.0
verification_method: BFS
reachability_method: approx
lp_solver: gurobi

Network Information:
Network type: MNIST_FNNsmall_tanh.onnx
Input Dimension: 784
Output Dimension: 10
Number of Layers: 6
Layer types:
Layer 0: <class 'StarV.layer.FullyConnectedLayer.FullyConnectedLayer'>
Layer 1: <class 'StarV.layer.TanSigLayer.TanSigLayer'>
Layer 2: <class 'StarV.layer.FullyConnectedLayer.FullyConnectedLayer'>
Layer 3: <class 'StarV.layer.TanSigLayer.TanSigLayer'>
Layer 4: <class 'StarV.layer.FullyConnectedLayer.FullyConnectedLayer'>
Layer 5: <class 'StarV.layer.TanSigLayer.TanSigLayer'>
Certifying the neural network with data 0
Computing layer 0 reachable set...
Number of stars/sparsestars: 1
Computing layer 1 reachable set...
Set parameter Username
Academic license - for non-commercial use only - expires 2024-02-18
Number of stars/sparsestars: 1
Computing layer 2 reachable set...
Number of stars/sparsestars: 1
Computing layer 3 reachable 

In [7]:
print('rb2: ', (rb2==1).sum())
print('vt2: ', vt2.sum())

rb2:  12
vt2:  2423.3567156791687


In [3]:
data_type = 'mnist'
net_size = 'small'
func = 'tanh'

depth_reduction = 3
relaxation_factor = 0.0

epsilon = 0.02
verification_method = 'BFS'
reachability_method = 'approx'
lp_solver = 'gurobi'

parallel_processing = None
show = True

net, image, label = load_sigmoidal_networks(data_type=data_type, net_size=net_size, func=func)

if show:
    print('epsilon: {}'.format(epsilon))
    print('depth reduction: {}'.format(depth_reduction))
    print('relaxation_factor: {}'.format(relaxation_factor))
    print('verification_method: {}'.format(verification_method))
    print('reachability_method: {}'.format(reachability_method))
    print('lp_solver: {}\n'.format(lp_solver))
    net.info()

rb3, vt3 =certifyRobustness (
    net = net, 
    input = image, 
    epsilon = epsilon, 
    veriMethod = verification_method, 
    reachMethod = reachability_method, 
    lp_solver = lp_solver, 
    pool = parallel_processing, 
    RF = relaxation_factor, 
    DR = depth_reduction, 
    show=show
)

epsilon: 0.02
depth reduction: 3
relaxation_factor: 0.0
verification_method: BFS
reachability_method: approx
lp_solver: gurobi

Network Information:
Network type: MNIST_FNNsmall_tanh.onnx
Input Dimension: 784
Output Dimension: 10
Number of Layers: 6
Layer types:
Layer 0: <class 'StarV.layer.FullyConnectedLayer.FullyConnectedLayer'>
Layer 1: <class 'StarV.layer.TanSigLayer.TanSigLayer'>
Layer 2: <class 'StarV.layer.FullyConnectedLayer.FullyConnectedLayer'>
Layer 3: <class 'StarV.layer.TanSigLayer.TanSigLayer'>
Layer 4: <class 'StarV.layer.FullyConnectedLayer.FullyConnectedLayer'>
Layer 5: <class 'StarV.layer.TanSigLayer.TanSigLayer'>
Certifying the neural network with data 0
Computing layer 0 reachable set...
Number of stars/sparsestars: 1
Computing layer 1 reachable set...
Number of stars/sparsestars: 1
Computing layer 2 reachable set...
Number of stars/sparsestars: 1
Computing layer 3 reachable set...
Number of stars/sparsestars: 1
Computing layer 4 reachable set...
Number of stars/sp

In [9]:
print('rb3: ', (rb3==1).sum())
print('vt3: ', vt3.sum())

rb3:  37
vt3:  2701.968254804611


In [4]:
depth_reduction = 0
relaxation_factor = 0.0

epsilon = 0.02
verification_method = 'BFS'
reachability_method = 'approx'
lp_solver = 'gurobi'

parallel_processing = None

net, image, label = load_sigmoidal_networks(data_type=data_type, net_size=net_size, func=func)

if show:
    print('epsilon: {}'.format(epsilon))
    print('depth reduction: {}'.format(depth_reduction))
    print('relaxation_factor: {}'.format(relaxation_factor))
    print('verification_method: {}'.format(verification_method))
    print('reachability_method: {}'.format(reachability_method))
    print('lp_solver: {}\n'.format(lp_solver))
    net.info()

rb0, vt0 =certifyRobustness (
    net = net, 
    input = image, 
    epsilon = epsilon, 
    veriMethod = verification_method, 
    reachMethod = reachability_method, 
    lp_solver = lp_solver, 
    pool = parallel_processing, 
    RF = relaxation_factor, 
    DR = depth_reduction, 
    show=show
)

epsilon: 0.02
depth reduction: 0
relaxation_factor: 0.0
verification_method: BFS
reachability_method: approx
lp_solver: gurobi

Network Information:
Network type: MNIST_FNNsmall_tanh.onnx
Input Dimension: 784
Output Dimension: 10
Number of Layers: 6
Layer types:
Layer 0: <class 'StarV.layer.FullyConnectedLayer.FullyConnectedLayer'>
Layer 1: <class 'StarV.layer.TanSigLayer.TanSigLayer'>
Layer 2: <class 'StarV.layer.FullyConnectedLayer.FullyConnectedLayer'>
Layer 3: <class 'StarV.layer.TanSigLayer.TanSigLayer'>
Layer 4: <class 'StarV.layer.FullyConnectedLayer.FullyConnectedLayer'>
Layer 5: <class 'StarV.layer.TanSigLayer.TanSigLayer'>
Certifying the neural network with data 0
Computing layer 0 reachable set...
Number of stars/sparsestars: 1
Computing layer 1 reachable set...
Number of stars/sparsestars: 1
Computing layer 2 reachable set...
Number of stars/sparsestars: 1
Computing layer 3 reachable set...
Number of stars/sparsestars: 1
Computing layer 4 reachable set...
Number of stars/sp

In [8]:
print('rb0: ', (rb0==1).sum())
print('vt0: ', vt0.sum())

rb0:  38
vt0:  2695.893021583557


In [15]:
vt0

array([26.33347, 26.8839 , 26.04896, 26.98853, 26.82799, 26.489  ,
       27.99842, 26.85141, 26.46736, 28.45977, 26.64461, 26.4112 ,
       26.93761, 27.55684, 27.10603, 26.78963, 25.90672, 26.43271,
       27.15335, 27.67322, 27.50042, 27.30356, 27.34336, 27.47502,
       27.51484, 27.20736, 27.3098 , 27.01525, 25.97657, 26.53755,
       26.38309, 26.7764 , 25.98287, 26.83349, 26.75176, 26.24727,
       27.8056 , 26.6083 , 26.60568, 27.23312, 26.11037, 26.97164,
       25.84323, 28.83193, 26.05512, 27.18803, 26.83118, 27.59753,
       27.2934 , 26.78752, 25.32995, 26.48955, 26.50797, 27.07539,
       27.45874, 28.32711, 26.19877, 25.30986, 27.47747, 27.58609,
       26.68955, 25.6223 , 26.16991, 26.81006, 26.97098, 26.77103,
       25.54702, 27.07278, 26.26362, 28.07864, 27.20292, 27.3613 ,
       28.04942, 26.59813, 28.33067, 26.86645, 26.83566, 26.95858,
       27.65997, 26.59596, 25.85855, 27.60439, 26.16779, 28.01873,
       28.28946, 26.66911, 26.90936, 26.53931, 26.24372, 28.26

In [25]:
import pickle
save_dir = 'sigmoidalNet_eval/' + net.type + '_eval.pkl'
print(save_dir)
with open(save_dir, 'wb') as f:  
    pickle.dump([rb0, vt0, epsilon, relaxation_factor, depth_reduction], f)

sigmoidalNet_eval/MNIST_FNNsmall_tanh.onnx_eval.pkl


In [27]:
f = open(save_dir, 'rb')
obj = pickle.load(f)
f.close()

print(len(obj))

5


In [31]:
import numpy as np
a = np.zeros((3,3,3))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [89]:
from StarV.set.sparsestar import SparseStar
S = SparseStar.rand(4, 5)
Sl, Su = S.getRanges()
print('l: ',Sl)
print('u: ',Su)
print('dim: ',S.dim)

l:  [0.25045 0.04573 0.45801 0.23664]
u:  [0.91711 0.82396 0.88256 0.91226]
dim:  4


In [95]:
import copy
RF = 0.5
delta = 0.95
layer = 'logsig'

dim = 10
lb = -np.random.rand(dim)
ub = np.random.rand(dim)

lb[np.random.randint(0,dim, 3)] = -0.96
ub[np.random.randint(0,dim, 3)] = 0.96
print('lb: ', lb)
print('ub: ', ub)

l = copy.deepcopy(lb)
u = copy.deepcopy(ub)

print('l.shape[0]: ', l.shape[0])
n1 = round( (1 - RF) * l.shape[0] )
print('n1: ', n1)

midx = np.argsort((u - l))[::-1]
print('midx: ', midx)
if layer in ['logsig', 'tansig']:
    print(layer)

lb:  [-0.33862 -0.20699 -0.91905 -0.96    -0.96    -0.97135 -0.25533 -0.80113
 -0.9077  -0.38207]
ub:  [0.96    0.96    0.08914 0.97748 0.22485 0.85237 0.5234  0.96    0.06062
 0.16526]
l.shape[0]:  10
n1:  5
midx:  [3 5 7 0 4 1 2 8 6 9]
logsig


In [99]:
print('l[midx]:\n', l[midx])
print('u[midx]:\n', u[midx])
print('diff:\n', u[midx]-l[midx])

midb = np.argwhere((l[midx] >= -delta) & (u[midx] <= delta))
print('midb: \n', midb)

n2 = n1
print('n1: ', n1)
check = midb.flatten().shape[0]
if n2 > check:
    n2 = check
print('n2: ', n2)

mid = midx[midb[0:n2]]
print('l[midb]:\n',l[mid])
print('u[midb]:\n',u[mid])

print('midx[midb[0:n2]]]: ', midx[midb[0:n2]])
print('mid: ', mid)

l[midx]:
 [-0.96    -0.97135 -0.80113 -0.33862 -0.96    -0.20699 -0.91905 -0.9077
 -0.25533 -0.38207]
u[midx]:
 [0.97748 0.85237 0.96    0.96    0.22485 0.96    0.08914 0.06062 0.5234
 0.16526]
diff:
 [1.93748 1.82372 1.76113 1.29862 1.18485 1.16699 1.00819 0.96832 0.77874
 0.54733]
midb: 
 [[6]
 [7]
 [8]
 [9]]
n1:  5
n2:  4
l[midb]:
 [[-0.91905]
 [-0.9077 ]
 [-0.25533]
 [-0.38207]]
u[midb]:
 [[0.08914]
 [0.06062]
 [0.5234 ]
 [0.16526]]
midx[midb[0:n2]]]:  [[2]
 [8]
 [6]
 [9]]
mid:  [[2]
 [8]
 [6]
 [9]]
